name: niagara_app
description: A new Flutter project from Niagara
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_route: ^7.9.2
  bloc_concurrency: ^0.2.4
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  get_it: ^7.6.7
  hive: ^4.0.0-dev.2
  injectable: ^2.3.5
  intl: ^0.18.1
  isar_flutter_libs: ^4.0.0-dev.13
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  path_provider: ^2.1.0
  retrofit: ^4.1.0
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  talker_bloc_logger: ^4.1.0
  talker_dio_logger: ^4.1.0
  talker_flutter: ^4.1.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  flutter_gen: ^5.4.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.5.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  slang_build_runner: ^3.30.0
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/core/utils/gen/

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/icons/bottom_bar/
    - assets/i18n/
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
