name: niagara_app
description: A new Flutter project from Niagara
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_route: ^7.9.1
  bloc_concurrency: ^0.2.4
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_hooks: ^0.20.5
  get_it: ^7.6.7
  injectable: ^2.4.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  retrofit: ^4.1.0
  talker: ^4.0.3
  talker_bloc_logger: ^4.0.3
  talker_dio_logger: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true