name: niagara_app
description: A new Flutter project from Niagara
publish_to: "none"

version: 6.0.31+654

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animated_snack_bar: ^0.4.0
  auto_route: ^8.0.0
  bloc_concurrency: ^0.2.4
  calendar_date_picker2: ^1.1.5
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  dio: ^5.4.1
  drift: ^2.17.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  extended_image: ^8.2.0
  firebase_analytics: ^11.0.1
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.1
  firebase_messaging: ^15.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_form_builder: ^9.2.1
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.1.1
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.15.2
  form_builder_validators: ^10.0.1
  freezed_annotation: ^2.4.1
  geolocator: ^13.0.1
  get_it: ^7.6.7
  hyphenatorx: ^1.5.11
  injectable: ^2.4.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.0
  mask_text_input_formatter: ^2.9.0
  mockito: ^5.4.4
  mutex: ^3.1.0
  package_info_plus: ^8.1.0
  path: ^1.9.0
  path_provider: ^2.1.0
  permission_handler: ^11.3.1
  photo_view: ^0.15.0
  pinput: ^5.0.0
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  shared_preferences: ^2.2.2
  slang: ^3.30.1
  slang_flutter: ^3.30.0
  sqlite3: ^2.4.2
  sqlite3_flutter_libs: ^0.5.0
  story: ^1.1.0
  stream_transform: ^2.1.0
  talker_bloc_logger: ^4.4.1
  talker_dio_logger: ^4.4.1
  talker_flutter: ^4.4.1
  url_launcher: ^6.2.6
  userx_flutter: ^1.3.7
  visibility_detector: ^0.4.0+2
  yandex_geocoder: ^2.3.1
  yandex_mapkit_lite: ^2.0.1
  yookassa_payments_flutter: ^1.7.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.8
  drift_dev: ^2.17.0
  flutter_gen: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.5.1
  json_serializable: ^6.7.1
  lint: ^2.3.0
  slang_build_runner: ^3.30.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true # запрещен альфа-канал в иконке для AppStore
  image_path: "assets/icons/app_icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_gen:
  output: lib/core/utils/gen/

  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bonus_status/
    - assets/images/about_bonuses/
    - assets/images/catalog/
    - assets/icons/
    - assets/icons/bottom_bar/
    - assets/icons/radio/
    - assets/icons/app_icon/
    - assets/i18n/
    - assets/lottie/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
